# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "artii", "~> 2.1"

gem "colorize", "~> 0.8.1"

gem "csv", "~> 3.2"

gem "terminal-table", "~> 3.0"

gem "tty-prompt", "~> 0.23.1"
